### ISSUE TITLE
Unable to render in a sidenav content

### ISSUE THREAD

**Issue by thxmike** [artbelikov/angular2-tree-diagram#19]
I am using this with Angular Material SideNav Content and it does not render

Here is my 
html
```
<div>
<tree-diagram [data]="data"></tree-diagram>
</div>
```

ts
```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-question-tree',
  templateUrl: './question-tree.component.html',
  styleUrls: ['./question-tree.component.scss']
})
export class QuestionTreeComponent implements OnInit {

  public _data = [
    {
      'guid': 'bc4c7a02-5379-4046-92be-12c67af4295a',
      'displayName': 'Elentrix',
      'children': [
        '85d412c2-ebc1-4d56-96c9-7da433ac9bb2',
        '28aac445-83b1-464d-9695-a4157dab6eac'
      ]
    },
    {
      'guid': '097b8d7c-e0d3-483d-9770-cb5306f7801c',
      'displayName': 'Insuron',
      'children': [
        'a2d8ec53-de45-4182-af74-58c27dc8c06c',
        '6ceb08e1-3da5-4532-a5d8-437fe714b685'
      ]
    }
  ];

  public get data() {
    return this._data;
  }

  constructor() { 
    console.log(this.data);
  }

  ngOnInit() {}
}
```

in my module, i have
```
import { TreeDiagram } from 'angular2-tree-diagram';
...
imports: [
...
TreeDiagram,
...
]
```
The module is nested but works with my other components fine.

The page is exposed via a router

I can see the chrome devtools, the data gets outputed in console.log but looking at the html elements it does not have any bindings. Not sure if it is a problem with late-binding or not.
There are no errors on the log.

I tried setting the data explicity instead of using a getter but this did not make a difference

Also, I do have the build setup so it is building the code as expected

**Comment by artbelikov** [comment]
Hi. Well, I can't help you with third party combinations. Getter won't make any difference. But this statement about getter demonstrates your involment with javascript. I don't want to be rude but you have to debug it yourself.On Jul 18, 2019 21:06, Michael A Rivera <notifications@github.com> wrote:I am using this with Angular Material SideNav Content and it does not render
Here is my
html
<div>
<tree-diagram [data]="data"></tree-diagram>
</div>

ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-question-tree',
  templateUrl: './question-tree.component.html',
  styleUrls: ['./question-tree.component.scss']
})
export class QuestionTreeComponent implements OnInit {

  public _data = [
    {
      'guid': 'bc4c7a02-5379-4046-92be-12c67af4295a',
      'displayName': 'Elentrix',
      'children': [
        '85d412c2-ebc1-4d56-96c9-7da433ac9bb2',
        '28aac445-83b1-464d-9695-a4157dab6eac'
      ]
    },
    {
      'guid': '097b8d7c-e0d3-483d-9770-cb5306f7801c',
      'displayName': 'Insuron',
      'children': [
        'a2d8ec53-de45-4182-af74-58c27dc8c06c',
        '6ceb08e1-3da5-4532-a5d8-437fe714b685'
      ]
    }
  ];

  public get data() {
    return this._data;
  }

  constructor() { 
    console.log(this.data);
  }

  ngOnInit() {}
}

in my module, i have
import { TreeDiagram } from 'angular2-tree-diagram';
...
imports: [
...
TreeDiagram,
...
]

The module is nested but works with my other components fine.
The page is exposed via a router
I can see the chrome devtools, the data gets outputed in console.log but looking at the html elements it does not have any bindings. Not sure if it is a problem with late-binding or not.
There are no errors.
I tried setting the data explicity instead of using a getter but this did not make a difference
Also, I do have the build setup so it is building the code as expected

**Comment by thxmike** [comment]
I see. On a side note, I am not sure what you mean by third party. Each item I describe above are all angular components that are installed via the Angular CLI and are part of the Angular suite of features.

- The SideNav is Angular Material, 
- The Router is the Angular Router
- The nesting is done with Angular Modules

I am using Angular 8.1.

Since I do not have a lot of experience with this component, and since I was trying to find something quick, I most likely will not try and debug this component. However, in the future, if I have a few hours to waste I will debug it and create a fork and pull request.
